#!/usr/bin/env perl
use strict;
use warnings;

use vDeck;
use CSFE;
use Getopt::Long;
use Net::DNS;

my $account = '';
my $domain = '';
GetOptions(
	'account=s' => \$account,
	'domain=s' => \$domain
) or print <<EOF;
 Help -

 	a - All domains on the account
	d - Specify domain
EOF

my $acct;
my $domains = [];
if ($account) {
	$acct = vDeck->new($account);
	foreach (@{$acct->domains()}) {
		push @$domains, $_->{'domain'};
	}
} elsif ($domain) {
	my $user = search($domain);
	$acct = vDeck->new($user);
	push @$domains, $domain;
}
my $info = $acct->tech_info();

my $dospf = 1;
my $dodkim = 1;
if (@$domains) {
	my $resolver = new Net::DNS::Resolver(
		nameservers => ['1.1.1.1', '1.0.0.1']
	);

	foreach my $domain (@$domains) {
		
		my $spf_check = $resolver->search($domain, 'TXT');
		my $dkim_record_name = "default._domainkey." . $domain;
		my $dkim_check = $resolver->search($dkim_record_name, "TXT");

		if ($spf_check and $dkim_check) {
			foreach my $x ($spf_check->answer) {
				if ($x->can('txtdata') and $x->txtdata =~ /$info->{'IPs'}/) {
					$dospf = 0;
				}
			}
			foreach my $x ($dkim_check->answer) {
				if ($x->can('txtdata') and $x->txtdata) {
					$dodkim = 0;
				}
			}

		}

		my @mx = mx($resolver, $domain);
		if (@mx) {
			foreach my $rr (@mx) {
				my $reply = $resolver->query($rr->exchange);
				if ($reply) {
					foreach my $i ($reply->answer) {
						if ($info->{'IPs'} eq $i->address) {
							print "$domain\n";
							add_spf($domain) if $dospf;
							add_dkim($domain) if $dodkim;
						}
					}
				}
			}
		}
	}
}


sub add_dkim {
	my $domain = shift // die "DKIM: Called without passing a domain.";
	my $dkim_record_name = "default._domainkey." . $domain;
	my $resolver2 = new Net::DNS::Resolver(
		nameservers => [$info->{'IPs'}]
	);
	my $dkim = $resolver2->search($dkim_record_name, "TXT");
	if ($dkim) {
		foreach my $x ($dkim->answer) {
			if ($x->can('txtdata') and $acct->dns_add($domain, 'txt', $domain, $x->txtdata)) {
				print "\t - Added SPF record\n";
			} else {
				print "\t - Failed SPF\n";
			}
		}
	}
}

sub add_spf {
	my $domain = shift // die "SPF: Called without passing a domain.";
	my $resolver2 = new Net::DNS::Resolver(
                nameservers => [$info->{'IPs'}]
        );
	my $spf = $resolver2->search($domain, "TXT");
	if ($spf) {
		foreach my $x ($spf->answer) {
			if ($x->can('txtdata') and $acct->dns_add($domain, 'txt', $domain, $x->txtdata)) {
				print "\t - Added SPF record\n";
			} else {
				print "\t - Failed SPF\n";
			}
		}
	}
}

